### PR TITLE
Returning Template Resource in TemplateDataResponse

### PR DESCRIPTION
**Pull request by emersonu**
Refactoring related to https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/issues/91.
Instead of returning templateData, TemplateDataResponse returns a Template.

The tests have not been implemented yet.

### CODE REVIEW

**Review by ignacio-chiazzo — COMMENTED** [review]
Thanks! this is exactly what I was looking for.

Are you planning to work on tests? I'm ok to merge it to the other branch now and work on test later; up to you.

**Comment by emersonu** [comment]
> Thanks! this is exactly what I was looking for.
> 
> Are you planning to work on tests? I'm ok to merge it to the other branch now and work on test later; up to you.

Yes, I'm working on the tests now.

**Comment by emersonu** [comment]
> Thanks! this is exactly what I was looking for.
> 
> Are you planning to work on tests? I'm ok to merge it to the other branch now and work on test later; up to you.

I started working on the tests, but I won't have time to continue work this week, if you want to continue where I left off, feel free!

**Comment by ignacio-chiazzo** [comment]
Thanks! I will merge it to the other branch and work on test separately

**Pull request merged**
