### PR TITLE
Send the current client instance to the initializer of the client res…

### PR DESCRIPTION
**Pull request by omarowns**
…ources methods

### CODE REVIEW

**Comment by ignacio-chiazzo** [comment]
Hey! I'm curious if this is an issue you're trying to solve.

**Comment by omarowns** [comment]
Hi @ignacio-chiazzo Yes, I started integrating this gem into one of my apps and noticed a strange behavior:
I'm doing a multi-tenant application so every tenant would be able to save their own Access Token/Sender ID/Business ID independently.
This means each tenant instantiates their own `WhatsappSdk::Api::Client`, however, when calling for `client.messages` it instantiates the `WhatsappSdk::Api::Messages` with a default client form `WhatsappSdk::Api::Request` instead of the client thats requesting that resource.

In my particular use case I had the client set to API version `v21.0` but the default client for `WhatsappSdk::Api::Request` was using `v19.0` and so I was getting a not very helpful error of my Sender ID not being found.

In this pull request/fix I'm sending the client instance to each of those initializers.

**Review by ignacio-chiazzo — COMMENTED** [review]
Thanks! 

Changes makes sense to me. Could you add tests? 

We're using the one set by configuration.
https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/blob/89a999af6c206834ca84f12a1fa0c8d82fd54de6/lib/whatsapp_sdk/api/request.rb#L9-L11

**Comment by omarowns** [comment]
For sure! I’ll see if I can add them today or this weekend 👍

**Comment by ignacio-chiazzo** [comment]
@omarowns Thanks for contributing! I have added the corresponding tests here https://github.com/omarowns/ruby_whatsapp_sdk/pull/2

**Comment by ignacio-chiazzo** [comment]
@omarowns The version `1.0.2` contains this feature  https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/releases/tag/v1.0.2

Thanks again.

**Pull request merged**
