### PR TITLE
Add location header to templates

### LINKED ISSUE #85: Add location header to templates
The API just released, adding the location to the template via headers:

API responses to [template creation and editing requests](https://developers.facebook.com/docs/whatsapp/business-management-api/message-templates) now include the template's status and category.

### PR DESCRIPTION
**Pull request by piscespieces**
This PR
- Creates a `Location` resource
- Adds a new `Location` type to the `ParameterObject` class

Example of how to send an existing template with a Location Header

```rb
# Creates Location Object resource [Location Object](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#location-object)
location = WhatsappSdk::Resource::Location.new(
  latitude: 25.779510,
  longitude: -80.338631,
  name: "My Miami Store",
  address: "820 NW 87th Ave, Miami, FL"
)
# Creates a Location Parameter Object
location_parameter = WhatsappSdk::Resource::ParameterObject.new(type: "location", location: location)

# Creates a Location Component
location_component = WhatsappSdk::Resource::Component.new(
  type: WhatsappSdk::Resource::Component::Type::Header,
  parameters: [location_parameter]
)

# Sends an existing template with a Location Component
messages_api.send_template(
  sender_id: 123,
  recipient_number: 123,
  name: "location_test",
  language: "en_US",
  components: [location_component]
)
```

[Location Object reference](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#location-object)
[Sending an existing template with location headers docs](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-message-templates/#example-request)

closes #85

### CODE REVIEW

**Review by ignacio-chiazzo — COMMENTED** [review]
Thank you! 

Could you add an example to
- [example.rb file](https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk/blob/main/example.rb#L78). This file is used for testing and as a guide. 
- Readme.

Could you add a test to Messages Api proving that `send_template` with the location header works as expected?

**Comment by piscespieces** [comment]
Sure! I will!

**Review by ignacio-chiazzo — COMMENTED** [review]
Thanks! 

Please remove changes on `Gemfile.lock`

**Comment by piscespieces** [comment]
> Thanks!
> 
> Please remove changes on `Gemfile.lock`

Oops!

**Review by ignacio-chiazzo — APPROVED** [review]
Thank you!

**Pull request merged**
